baseURL = "/"
languageCode = "en-gb"
title = "Catherine Bacon"
theme = "kube"
description = "Learning to code. <br/>Studying fullstack JavaScript web development.<br/>About to start a 12 week internship in June 2017."
Paginate = 4
publishDir = "docs"
[Params]
  RSSLink = "/index.xml"
  author = "Catherine Bacon" # add your company name
  github = "CatherineBacon" # add your github profile name
  email = "catherine.bacon@gmail.com"
  image = "img/profile_pic.jpg"

[[menu.main]]
    name = "Portfolio"
    weigth = -120
    url = "/portfolio/"
[[menu.main]]
    name = "Blog"
    weight = -110
    url = "/blog/"
[[menu.main]]
    name = "About"
    weight = -200
    url = "/about/"
